// Please do not arbitrarily modify it.
// This file is automatically generated by the subpabase command.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json }
  | Json[];

export interface Database {
  public: {
    Tables: {
      category: {
        Row: {
          category_name: string;
          created_at: string | null;
          id: string;
          is_active: boolean;
        };
        Insert: {
          category_name?: string;
          created_at?: string | null;
          id?: string;
          is_active?: boolean;
        };
        Update: {
          category_name?: string;
          created_at?: string | null;
          id?: string;
          is_active?: boolean;
        };
      };
      research_list: {
        Row: {
          category_id: string | null;
          closed_at: string | null;
          created_at: string;
          id: string;
          research_actvie: boolean;
          research_name: string;
        };
        Insert: {
          category_id?: string | null;
          closed_at?: string | null;
          created_at?: string;
          id?: string;
          research_actvie?: boolean;
          research_name: string;
        };
        Update: {
          category_id?: string | null;
          closed_at?: string | null;
          created_at?: string;
          id?: string;
          research_actvie?: boolean;
          research_name?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}
